type User {
  id: ID!
  name: String!
  lastName: String!
  userName: String
  email: String!
  password: String
  token: String!
  pets: [Pet]!
}

type Pet {
  name: String!
  petType: Int!
  birthday: String!
  isAdopted: Boolean
  adoptionDate: String
  height: Float!
  length: Float!
  weight: Float!
  gender: Boolean!
  hairColor: Int
  eyeColor: Int
  hasHeterochromia: Boolean
  user: User
}