## USERS
type Token {
  token: String!
}

type User {
  id: ID!
  name: String!
  lastName: String!
  userName: String
  email: String!
  password: String
  tokens: [Token]!
  pets: [Pet]!
}

## PETS
type Pet {
  id: ID!
  name: String!
  petType: AuxiliaryData!
  birthday: String
  isAdopted: Boolean!
  adoptionDate: String
  weight: Float
  gender: Boolean!
  hairColors: [AuxiliaryData]
  hasHeterochromia: Boolean
  eyeColors: [AuxiliaryData]
  passedAway: Boolean!
  user: User
  events: [Event]
}

## EVENT
type Event {
  id: ID!
  description: String!
  date: String!
  associatedPets: [Pet]!
}

## OTHER
type AuxiliaryData {
  id: ID!
  name: String!
}

type AmountData {
  name: String!
  quantity: Int!
}