type User {
  id: ID!
  name: String!
  lastName: String!
  userName: String
  email: String!
  password: String
  token: String!
  pets: [Pet]!
}

type Pet {
  id: ID!
  name: String!
  petType: AuxiliaryData!
  birthday: String
  isAdopted: Boolean!
  adoptionDate: String
  height: Float
  length: Float
  weight: Float
  gender: String!
  hairColors: [AuxiliaryData]
  hasHeterochromia: Boolean
  eyeColors: [AuxiliaryData]
  user: User
}

type AuxiliaryData {
  id: ID!
  name: String!
}