input UserInput {
  name: String!
  lastName: String!
  userName: String!
  email: String!
  password: String!
}

input PetInput {
  id: ID
  name: String!
  petType: ID!
  birthday: String
  isAdopted: Boolean!
  adoptionDate: String
  height: Float
  length: Float
  weight: Float
  gender: String!
  hairColors: [ID]
  hasHeterochromia: Boolean
  eyeColors: [ID]
}