type Query {
  getUser: User!
  getPetTypes: [AuxiliaryData]!
  getColors: [AuxiliaryData]!
  getMyPets: [Pet]!
  getPet(id: ID!): Pet
}

type Mutation {
  loginUser(email: String!, password: String!): User
  createUser(newUser: UserInput): User
  updateUser(name: String!, lastName: String!): User
  updatePass(oldPass: String!, newPass: String!): Boolean
  createPet(petInfo: PetInput!): Pet
  updatePet(petInfo: PetInput!): Boolean!
  logout: Boolean!
  # logoutAll: Boolean!
}