type Query {
  getUser: User!
  getPetTypes: [AuxiliaryData]!
  getColors: [AuxiliaryData]!
  getMyPets(search: String): [Pet]!
  getPet(id: ID!): Pet
  getMyPetsPopulation: [AmountData]
  getMyPetEvents(petId: ID!): [Event]
}

type Mutation {
  loginUser(userPayload: UserLoginPayload!): User
  createUser(userPayload: UserCreatePayload!): UserCreateResponse
  updateUser(userPayload: UserUpdatePayload!): User
  updatePass(passPayload: UserPassChangePayload!): Boolean
  logout: Boolean!
  createPet(petPayload: PetCreatePayload!): Pet
  updatePet(id: String!, petPayload: PetCreatePayload!): Boolean!
  createEvent(eventPayload: EventCreatePayload!): Event
}