type Query {
  ## USERS
  getUser: UserCreateResponse!
  ## PETS
  getMyPets(search: String): [Pet]!
  getPet(petId: ID!): Pet
  getMyPetsPopulation: [AmountData]
  getPetTypes: [AuxiliaryData]!
  getColors: [AuxiliaryData]!
  ## EVENTS
  getMyPetEvents(petId: ID!): [Event]
  getEvent(eventId: ID!): Event
}

type Mutation {
  ## USERS
  loginUser(payload: UserLoginPayload!): LoginUserResponse
  createUser(payload: UserCreatePayload!): UserCreateResponse
  updateUser(payload: UserUpdatePayload!): UserCreateResponse
  updatePass(payload: UserPassUpdatePayload!): Boolean
  logout: Boolean!
  ## PETS
  createPet(payload: PetCreatePayload!): Pet
  updatePet(id: String!, payload: PetCreatePayload!): Boolean!
  ## EVENTS
  createEvent(payload: EventCreatePayload!): Event
}